### ISSUE TITLE
Quick checklist Ticket for Tracking ad-hoc tasks w/c 29/01/2024

### ISSUE THREAD

**Issue by pratik-IDWT** [In-Data-We-Trust/Marketing-and-Branding#55]
Ticket to write and log quick checklist tasks

- [x] Contact Ravneet
- [x] Message Tom
- [x] Message Angus
- [x] Message David Swallow
- [x] Create Lead tracking spreadsheet across LinkedIn, text, emails, and whatsapp 
- [x] Review saved contracts on LI and apply
- [x] Read up on Jason Package
- [x] Who We Do respond
- [x] Module 1 - Get Stability
- [x] Read Faris's blog posts about early days marketing
